    - name: Install Qt for Android using aqtinstall
      run: |
        echo "Installing aqtinstall..."
        python -m pip install aqtinstall
        
        echo "Installing Qt for Android version ${{ env.QT_VERSION }} for ${{ env.QT_ANDROID_ARCH }} on host Linux..."
        # Corrected: First argument is the host OS (linux), second is the target platform (android)
        aqt install-qt linux android ${{ env.QT_VERSION }} ${{ env.QT_ANDROID_ARCH }} -m qt6core qt6gui qt6widgets qtpyshared qt6svg
        
        # Set QT_PATH for subsequent steps
        # The default installation path for aqt is $HOME/Qt
        INSTALLED_QT_PATH="$HOME/Qt/${{ env.QT_VERSION }}/${{ env.QT_ANDROID_ARCH }}"
        echo "INSTALLED_QT_PATH=${INSTALLED_QT_PATH}"
        
        if [ ! -d "$INSTALLED_QT_PATH" ]; then
          echo "::error::Qt for Android path not found after installation: $INSTALLED_QT_PATH. Listing $HOME/Qt..."
          ls -R $HOME/Qt || echo "$HOME/Qt does not exist."
          exit 1
        fi
        
        echo "QT_PATH=${INSTALLED_QT_PATH}" >> $GITHUB_ENV
        echo "Qt for Android installed at: ${INSTALLED_QT_PATH}"
        
        # Add Qt tools to PATH for subsequent steps
        echo "${INSTALLED_QT_PATH}/bin" >> $GITHUB_PATH
        echo "Added ${INSTALLED_QT_PATH}/bin to GITHUB_PATH"
